manifest:
  self:
    west-commands: scripts/west-commands.yml

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v4.3.0
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - cmsis
          - cmsis_6      # required by the ARM port
          - hal_nordic # required by the board (Nordic based)\
          - hal_atmel
          - hal_espressif
          - hal_st       # required by ST IMU sensor drivers
          - mcuboot